// ============================================
// Language Translations - Sophie手帐
// ============================================

var translations = {
    zh: {
        // Navigation
        logo: "Sophie手帐",
        "nav.colors": "配色灵感",
        "nav.mbti": "手帐人格",
        "nav.planner": "手帐设计",
        "nav.track": "今日打卡",
        "nav.resources": "设计思路",
        "nav.learn": "了解ADHD",
        "nav.about": "我的故事",
        "nav.qa": "常见问题",

        // Hero
        "hero.greeting": "你好，我是",
        "hero.subtitle": "手帐是记录生活的方式<br>每个人都可以找到适合自己的记录风格",
        "hero.mbtiBtn": "测测你的手帐人格",
        "hero.plannerBtn": "设计适合你的手帐",
        "hero.tracking": "今日打卡",
        "hero.resourcesBtn": "设计思路",
        "hero.learnMore": "了解ADHD",
        "hero.aboutBtn": "我的故事",
        "hero.scroll": "向下",

        // Track Section
        "track.label": "~ 打卡 & 主题 ~",
        "track.title": "记录你的手帐旅程",
        "track.themeName": "四月：记录感恩",
        "track.themeDesc": "每天写下一件让你感恩的事",

        // Resources
        "resources.label": "~ 素材库 ~",
        "resources.title": "设计思路",
        "resources.subtitle": "免费模板与语录",
        "resources.colors": "配色灵感",
        "resources.layout": "排版技巧",
        "resources.designIdeas": "设计思路",
        "resources.materials": "素材下载",

        // Color Quiz
        "color.quizTitle": "你喜欢什么风格的颜色？",
        "color.stylesTitle": "经典艺术风格色系",

        // Modal
        "modal.tab.adhd": "ADD/ADHD",
        "modal.tab.infp": "P型人格",
        "modal.adhd.title": "什么是ADD/ADHD？",
        "modal.adhd.intro": "ADD/ADHD不是缺陷，而是大脑运作方式不同。",
        "modal.adhd.item1": "注意力容易分散，但也可能超聚焦",
        "modal.adhd.item2": "时间感模糊，忘记做了什么、要做什么",
        "modal.adhd.item3": "传统计划方式常常失效",
        "modal.adhd.tip": "<strong>手帐可以是你的锚点：</strong>记录让你看到时间是怎么过的，不需要完美执行计划。",
        "modal.infp.title": "什么是P型人格？",
        "modal.infp.intro": "P型（感知型）是MBTI中的一种偏好，代表灵活、随性、适应性强。",
        "modal.infp.item1": "追求意义和真实性",
        "modal.infp.item2": "内心世界丰富",
        "modal.infp.item3": "不喜欢被规则束缚",
        "modal.infp.tip": "<strong>P型特质：</strong>P型人喜欢灵活，与其强迫自己计划，不如用记录来了解自己。",

        // About
        "about.label": "~ 关于我 ~",
        "about.title": "我的故事",
        "about.photoPlaceholder": "你的照片",
        "about.intro": "我是 Sophie，一个曾经觉得自己做不好手帐的人。",
        "about.story1": "最早开始做手帐的时候，我发现自己总是坚持不下来——经常忘记要做什么，也忘了做了什么，日期对我来说总是模糊的。",
        "about.story2": "我试过各种计划表、打卡本，但每次都是写了几天就放弃。我以为是我不够自律，不够坚持。",
        "about.story3": "后来我才明白：不是我不适合做手帐，是我一直在用不适合我的方式做手帐。",
        "about.story4": "现在我帮助和我一样的人——注意力容易分散的人、不喜欢被规则束缚的人——找到属于自己的记录方式。用自己的风格，记录属于自己的时间。",

        // Planner Wizard
        "planner.label": "~ 找到你的风格 ~",
        "planner.title": "手帐风格测试",
        "planner.subtitle": "几个问题，帮你找到适合的方式",
        "planner.q1Title": "你是谁？",
        "planner.bgStudent": "学生",
        "planner.bgWorker": "上班族",
        "planner.bgParent": "宝妈/家长",
        "planner.bgFreelancer": "自由职业",
        "planner.q2pjTitle": "你是J还是P？",
        "planner.q2pjHint": "MBTI性格类型中的判断维度",
        "planner.jType": "J型（判断型）",
        "planner.jTypeDesc": "喜欢计划、按规则执行、享受规律",
        "planner.pType": "P型（感知型）",
        "planner.pTypeDesc": "喜欢灵活、随性而行、不喜被束缚",
        "planner.q3adhdTitle": "你的注意力特点？",
        "planner.q3adhdHint": "ADD/ADHD倾向自评",
        "planner.adhdNone": "无明显倾向",
        "planner.adhdNoneDesc": "注意力较稳定，计划能正常执行",
        "planner.adhdMild": "轻微倾向",
        "planner.adhdMildDesc": "偶尔分心、忘记任务、时间感模糊",
        "planner.adhdSignificant": "明显倾向",
        "planner.adhdSignificantDesc": "经常分心/超聚焦、时间感很模糊",
        "planner.q4Title": "你想用手帐做什么？",
        "planner.q4Hint": "可多选",
        "planner.goalTasks": "管理任务",
        "planner.goalTime": "记录时间",
        "planner.goalHabits": "追踪习惯",
        "planner.goalFeelings": "记录感受",
        "planner.goalReading": "读书/观影记录",
        "planner.q5Title": "纸质还是数字？",
        "planner.mediumPaper": "纸质手帐",
        "planner.mediumPaperDesc": "手写触感、实体收藏、可自由排版",
        "planner.mediumDigital": "数字手帐",
        "planner.mediumDigitalDesc": "随时记录、方便修改、多设备同步",
        "planner.q6Title": "计划会经常改变吗？",
        "planner.q6Hint": "灵活性程度",
        "planner.flexNever": "基本不变",
        "planner.flexNeverDesc": "计划制定后基本能按计划执行",
        "planner.flexOccasional": "偶尔小变",
        "planner.flexOccasionalDesc": "计划有时需要微调",
        "planner.flexFrequent": "常有小变",
        "planner.flexFrequentDesc": "计划经常会调整，但大方向不变",
        "planner.flexVeryFrequent": "经常大变",
        "planner.flexVeryFrequentDesc": "计划几乎没法提前定，随性为主",
        "planner.flexVeryFrequentTip": "💡 这种情况建议手机App",
        "planner.q7Title": "排版偏好？",
        "planner.layoutCompact": "紧凑型",
        "planner.layoutCompactDesc": "一页多内容、信息密集、实用",
        "planner.layoutSpacious": "宽松型",
        "planner.layoutSpaciousDesc": "留白多、可装饰、美观",
        "planner.q8Title": "同时记录几件事？",
        "planner.q8Hint": "一天内想记录的内容数量",
        "planner.multiOne": "一件事",
        "planner.multiOneDesc": "专注记录最重要的事",
        "planner.multiFew": "几件事",
        "planner.multiFewDesc": "2-5件事，常见情况",
        "planner.multiMany": "很多事",
        "planner.multiManyDesc": "喜欢记录每件小事和细节",

        // Result
        "planner.recommended": "推荐",
        "planner.resultTitle": "适合你的手帐类型",
        "planner.resultNote": "💡 你可以组合2-3种类型使用\n截图和图片可以自己添加到相应位置",
        "planner.restart": "重新测试",
        "planner.getHelp": "需要帮助？联系我",
        "planner.prev": "← 上一步",
        "planner.next": "下一步 →",
        "planner.yourProfile": "你的特点",
        "planner.recommendedTypes": "推荐类型",
        "planner.variant": "推荐变体",
        "planner.combinations": "组合建议",
        "planner.multiGoalTip": "你的目标较多，可以组合使用多种类型",
        "planner.pAdhdTip": "P型+ADHD：建议以记录为主，计划为辅。先用Timeline观察时间，再慢慢加入To-do",
        "planner.highFlexTip": "计划变化很频繁：推荐活页本或手机App，方便随时调整",
        "planner.paperFlexConflict": "纸质偏好但计划变化频繁：考虑活页本，或纸质+手机App组合",

        // Calendar
        "calendar.label": "~ 打卡日历 ~",
        "calendar.title": "手帐打卡",
        "calendar.subtitle": "点击日期标记",
        "calendar.days": "天",
        "calendar.streak": "连续",

        // Layout
        "layout.label": "~ 排版技巧 ~",
        "layout.title": "手帐排版基础",
        "layout.subtitle": "简单的排版理论，让你的手帐更好看",
        "layout.whitespace.title": "留白原则",
        "layout.whitespace.desc": "页面至少要有<strong>30%的空白</strong>，不要填满每一寸空间。留白让页面呼吸，更容易阅读。",
        "layout.alignment.title": "对齐原则",
        "layout.alignment.desc": "选择一种对齐方式并<strong>保持一致</strong>。可以全左对齐、全居中，但不要混用。",
        "layout.hierarchy.title": "视觉层次",
        "layout.hierarchy.desc": "标题<strong>大且醒目</strong>，正文<strong>适中</strong>，注释<strong>小且轻</strong>。让读者一眼看到重点。",
        "layout.proportion.title": "图文比例",
        "layout.proportion.desc": "图片和装饰元素<strong>不超过40%</strong>面积。文字才是手帐的核心，不要被图片淹没。",
        "layout.repetition.title": "重复元素",
        "layout.repetition.desc": "用<strong>相同的装饰元素</strong>（如小星星、圆点）作为标记，让整本手帐更有整体感。",
        "layout.colors.title": "颜色数量",
        "layout.colors.desc": "一页手帐<strong>不超过3种颜色</strong>。太多颜色会显得杂乱，反而不好看。",
        "layout.mainTip": "最重要的：<strong>排版是为了让内容更容易阅读</strong>，不是为了好看而已。如果不确定，就保持简洁！",

        // Q&A
        "qa.label": "~ 问答专区 ~",
        "qa.title": "常见问题解答",
        "qa.subtitle": "新手常见疑问，帮你快速上手手帐",

        // Contact
        "contact.label": "~ 联系我 ~",
        "contact.title": "一起探索手帐",
        "contact.intro": "想定制专属手帐系统？有问题想聊？欢迎联系我。",
        "contact.formName": "名字",
        "contact.formEmail": "邮箱",
        "contact.formMessage": "想说的话",
        "contact.formSubmit": "发送",

        // Footer
        "footer.tagline": "Sophie手帐 ~ 为创意心灵而设计",
        "footer.copyright": "Sophie手帐 · since 2024"
    },

    tw: {
        // Navigation
        logo: "Sophie手帳",
        "nav.colors": "配色靈感",
        "nav.mbti": "手帳人格",
        "nav.planner": "手帳設計",
        "nav.track": "今日打卡",
        "nav.resources": "設計思路",
        "nav.learn": "了解ADHD",
        "nav.about": "我的故事",
        "nav.qa": "常見問題",

        // Hero
        "hero.greeting": "你好，我是",
        "hero.subtitle": "手帳是記錄生活的方式<br>每個人都可以找到適合自己的記錄風格",
        "hero.mbtiBtn": "測測你的手帳人格",
        "hero.plannerBtn": "設計適合你的手帳",
        "hero.tracking": "今日打卡",
        "hero.resourcesBtn": "設計思路",
        "hero.learnMore": "了解ADHD",
        "hero.aboutBtn": "我的故事",
        "hero.scroll": "向下",

        // Track Section
        "track.label": "~ 打卡 & 主題 ~",
        "track.title": "記錄你的手帳旅程",
        "track.themeName": "四月：記錄感恩",
        "track.themeDesc": "每天寫下一件讓你感恩的事",

        // Resources
        "resources.label": "~ 素材庫 ~",
        "resources.title": "設計思路",
        "resources.subtitle": "免費模板與語錄",
        "resources.colors": "配色靈感",
        "resources.layout": "排版技巧",
        "resources.designIdeas": "設計思路",
        "resources.materials": "素材下載",

        // Color Quiz
        "color.quizTitle": "你喜歡什麼風格的顏色？",
        "color.stylesTitle": "經典藝術風格色系",

        // Modal
        "modal.tab.adhd": "ADD/ADHD",
        "modal.tab.infp": "P型人格",
        "modal.adhd.title": "什麼是ADD/ADHD？",
        "modal.adhd.intro": "ADD/ADHD不是缺陷，而是大腦運作方式不同。",
        "modal.adhd.item1": "注意力容易分散，但也可能超聚焦",
        "modal.adhd.item2": "時間感模糊，忘記做了什麼、要做什麼",
        "modal.adhd.item3": "傳統計劃方式常常失效",
        "modal.adhd.tip": "<strong>手帳可以是你的錨點：</strong>記錄讓你看到時間是怎麼過的，不需要完美執行計劃。",
        "modal.infp.title": "什麼是P型人格？",
        "modal.infp.intro": "P型（感知型）是MBTI中的一種偏好，代表靈活、隨性、適應性強。",
        "modal.infp.item1": "追求意義和真實性",
        "modal.infp.item2": "內心世界豐富",
        "modal.infp.item3": "不喜歡被規則束縛",
        "modal.infp.tip": "<strong>P型特質：</strong>P型人喜歡靈活，與其強迫自己計劃，不如用記錄來了解自己。",

        // About
        "about.label": "~ 關於我 ~",
        "about.title": "我的故事",
        "about.photoPlaceholder": "你的照片",
        "about.intro": "我是 Sophie，一個曾經覺得自己做不好手帳的人。",
        "about.story1": "最早開始做手帳的時候，我發現自己總是堅持不下來——經常忘記要做什麼，也忘了做了什麼，日期對我來來說總是模糊的。",
        "about.story2": "我試過各種計劃表、打卡本，但每次都是寫了幾天就放棄。我以為是我不夠自律，不夠堅持。",
        "about.story3": "後來我才明白：不是我不適合做手帳，是我一直在用不適合我的方式做手帳。",
        "about.story4": "現在我幫助和我一樣的人——注意力容易分散的人、不喜歡被規則束縛的人——找到屬於自己的記錄方式。用自己的風格，記錄屬於自己的時間。",

        // Planner Wizard
        "planner.label": "~ 找到你的風格 ~",
        "planner.title": "手帳風格測試",
        "planner.subtitle": "幾個問題，幫你找到適合的方式",
        "planner.q1Title": "你是誰？",
        "planner.bgStudent": "學生",
        "planner.bgWorker": "上班族",
        "planner.bgParent": "寶媽/家長",
        "planner.bgFreelancer": "自由職業",
        "planner.q2pjTitle": "你是J還是P？",
        "planner.q2pjHint": "MBTI性格類型中的判斷維度",
        "planner.jType": "J型（判斷型）",
        "planner.jTypeDesc": "喜歡計劃、按規則執行、享受規律",
        "planner.pType": "P型（感知型）",
        "planner.pTypeDesc": "喜歡靈活、隨性而行、不喜被束縛",
        "planner.q3adhdTitle": "你的注意力特點？",
        "planner.q3adhdHint": "ADD/ADHD傾向自評",
        "planner.adhdNone": "無明顯傾向",
        "planner.adhdNoneDesc": "注意力較穩定，計劃能正常執行",
        "planner.adhdMild": "輕微傾向",
        "planner.adhdMildDesc": "偶爾分心、忘記任務、時間感模糊",
        "planner.adhdSignificant": "明顯傾向",
        "planner.adhdSignificantDesc": "經常分心/超聚焦、時間感很模糊",
        "planner.q4Title": "你想用手帳做什麼？",
        "planner.q4Hint": "可多選",
        "planner.goalTasks": "管理任務",
        "planner.goalTime": "記錄時間",
        "planner.goalHabits": "追蹤習慣",
        "planner.goalFeelings": "記錄感受",
        "planner.goalReading": "讀書/觀影記錄",
        "planner.q5Title": "紙質還是數位？",
        "planner.mediumPaper": "紙質手帳",
        "planner.mediumPaperDesc": "手寫觸感、實體收藏、可自由排版",
        "planner.mediumDigital": "數位手帳",
        "planner.mediumDigitalDesc": "隨時記錄、方便修改、多設備同步",
        "planner.q6Title": "計劃會經常改變嗎？",
        "planner.q6Hint": "靈活性程度",
        "planner.flexNever": "基本不變",
        "planner.flexNeverDesc": "計劃制定後基本能按計劃執行",
        "planner.flexOccasional": "偶爾小變",
        "planner.flexOccasionalDesc": "計劃有時需要微調",
        "planner.flexFrequent": "常有小變",
        "planner.flexFrequentDesc": "計劃經常會調整，但大方向不變",
        "planner.flexVeryFrequent": "經常大變",
        "planner.flexVeryFrequentDesc": "計劃幾乎沒法提前定，隨性為主",
        "planner.flexVeryFrequentTip": "💡 這種情況建議手機App",
        "planner.q7Title": "排版偏好？",
        "planner.layoutCompact": "緊湊型",
        "planner.layoutCompactDesc": "一頁多內容、信息密集、實用",
        "planner.layoutSpacious": "寬鬆型",
        "planner.layoutSpaciousDesc": "留白多、可裝飾、美觀",
        "planner.q8Title": "同時記錄幾件事？",
        "planner.q8Hint": "一天內想記錄的內容數量",
        "planner.multiOne": "一件事",
        "planner.multiOneDesc": "專注記錄最重要的事",
        "planner.multiFew": "幾件事",
        "planner.multiFewDesc": "2-5件事，常見情況",
        "planner.multiMany": "很多事",
        "planner.multiManyDesc": "喜歡記錄每件小事和細節",

        // Result
        "planner.recommended": "推薦",
        "planner.resultTitle": "適合你的手帳類型",
        "planner.resultNote": "💡 你可以組合2-3種類型使用\n截圖和圖片可以自己添加到相應位置",
        "planner.restart": "重新測試",
        "planner.getHelp": "需要幫助？聯繫我",
        "planner.prev": "← 上一步",
        "planner.next": "下一步 →",
        "planner.yourProfile": "你的特點",
        "planner.recommendedTypes": "推薦類型",
        "planner.variant": "推薦變體",
        "planner.combinations": "組合建議",
        "planner.multiGoalTip": "你的目標較多，可以組合使用多種類型",
        "planner.pAdhdTip": "P型+ADHD：建議以記錄為主，計劃為輔。先用Timeline觀察時間，再慢慢加入To-do",
        "planner.highFlexTip": "計劃變化很頻繁：推薦活頁本或手機App，方便隨時調整",
        "planner.paperFlexConflict": "紙質偏好但計劃變化頻繁：考慮活頁本，或紙質+手機App組合",

        // Calendar
        "calendar.label": "~ 打卡日曆 ~",
        "calendar.title": "手帳打卡",
        "calendar.subtitle": "點擊日期標記",
        "calendar.days": "天",
        "calendar.streak": "連續",

        // Layout
        "layout.label": "~ 排版技巧 ~",
        "layout.title": "手帳排版基礎",
        "layout.subtitle": "簡單的排版理論，讓你的手帳更好看",
        "layout.whitespace.title": "留白原則",
        "layout.whitespace.desc": "頁面至少要有<strong>30%的空白</strong>，不要填滿每一寸空間。留白讓頁面呼吸，更容易閱讀。",
        "layout.alignment.title": "對齊原則",
        "layout.alignment.desc": "選擇一種對齊方式並<strong>保持一致</strong>。可以全左對齊、全居中，但不要混用。",
        "layout.hierarchy.title": "視覺層次",
        "layout.hierarchy.desc": "標題<strong>大且醒目</strong>，正文<strong>適中</strong>，註釋<strong>小且輕</strong>。讓讀者一眼看到重點。",
        "layout.proportion.title": "圖文比例",
        "layout.proportion.desc": "圖片和裝飾元素<strong>不超過40%</strong>面積。文字才是手帳的核心，不要被圖片淹沒。",
        "layout.repetition.title": "重複元素",
        "layout.repetition.desc": "用<strong>相同的裝飾元素</strong>（如小星星、圓點）作為標記，讓整本手帳更有整體感。",
        "layout.colors.title": "顏色數量",
        "layout.colors.desc": "一頁手帳<strong>不超過3種顏色</strong>。太多顏色會顯得雜亂，反而不好看。",
        "layout.mainTip": "最重要的：<strong>排版是為了讓內容更容易閱讀</strong>，不是為了好看而已。如果不確定，就保持簡潔！",

        // Q&A
        "qa.label": "~ 問答專區 ~",
        "qa.title": "常見問題解答",
        "qa.subtitle": "新手常見疑問，幫你快速上手手帳",

        // Contact
        "contact.label": "~ 聯繫我 ~",
        "contact.title": "一起探索手帳",
        "contact.intro": "想定製專屬手帳系統？有問題想聊？歡迎聯繫我。",
        "contact.formName": "名字",
        "contact.formEmail": "郵箱",
        "contact.formMessage": "想說的話",
        "contact.formSubmit": "發送",

        // Footer
        "footer.tagline": "Sophie手帳 ~ 為創意心灵而設計",
        "footer.copyright": "Sophie手帳 · since 2024"
    },

    en: {
        // Navigation
        logo: "Sophie Planner",
        "nav.colors": "Color Palette",
        "nav.mbti": "Journal MBTI",
        "nav.planner": "Design Quiz",
        "nav.track": "Check-in",
        "nav.resources": "Design Guide",
        "nav.learn": "Learn ADHD",
        "nav.about": "My Story",
        "nav.qa": "FAQ",

        // Hero
        "hero.greeting": "Hi, I'm",
        "hero.subtitle": "Journaling is a way to record life<br>Everyone can find their own journaling style",
        "hero.mbtiBtn": "Test Your Journal Personality",
        "hero.plannerBtn": "Design Your Journal",
        "hero.tracking": "Today's Check-in",
        "hero.resourcesBtn": "Design Guide",
        "hero.learnMore": "Learn ADHD",
        "hero.aboutBtn": "My Story",
        "hero.scroll": "Scroll",

        // Track Section
        "track.label": "~ Check-in & Theme ~",
        "track.title": "Track Your Journey",
        "track.themeName": "April: Gratitude",
        "track.themeDesc": "Write one thing you're grateful for each day",

        // Resources
        "resources.label": "~ Material Library ~",
        "resources.title": "Design Ideas",
        "resources.subtitle": "Free Templates & Quotes",
        "resources.colors": "Color Palette",
        "resources.layout": "Layout Tips",
        "resources.designIdeas": "Design Ideas",
        "resources.materials": "Downloads",

        // Color Quiz
        "color.quizTitle": "What color style do you like?",
        "color.stylesTitle": "Classic Art Style Palettes",

        // Modal
        "modal.tab.adhd": "ADD/ADHD",
        "modal.tab.infp": "P-Type",
        "modal.adhd.title": "What is ADD/ADHD?",
        "modal.adhd.intro": "ADD/ADHD is not a defect, just a different way the brain works.",
        "modal.adhd.item1": "Easily distracted, but can also hyperfocus",
        "modal.adhd.item2": "Time sense is fuzzy, forget what to do and what was done",
        "modal.adhd.item3": "Traditional planning often fails",
        "modal.adhd.tip": "<strong>Planner can be your anchor:</strong> Recording lets you see how time passed, without needing perfect execution.",
        "modal.infp.title": "What is P-Type?",
        "modal.infp.intro": "P-Type (Perceiving) is a preference in MBTI, representing flexibility, spontaneity, and adaptability.",
        "modal.infp.item1": "Seek meaning and authenticity",
        "modal.infp.item2": "Rich inner world",
        "modal.infp.item3": "Don't like being bound by rules",
        "modal.infp.tip": "<strong>P-Type Traits:</strong> P-types prefer flexibility. Instead of forcing yourself to plan, use recording to understand yourself.",

        // About
        "about.label": "~ About Me ~",
        "about.title": "My Story",
        "about.photoPlaceholder": "Your Photo",
        "about.intro": "I'm Sophie, someone who once thought I couldn't journal well.",
        "about.story1": "When I first started journaling, I couldn't keep it up - I often forgot what to do and what I had done. Dates were always fuzzy to me.",
        "about.story2": "I tried various planners and trackers, but I'd give up after a few days each time. I thought I wasn't disciplined enough, not persistent enough.",
        "about.story3": "Later I realized: it wasn't that I wasn't suited for journaling, it was that I was using methods that didn't suit me.",
        "about.story4": "Now I help people like me - those whose attention wanders, those who don't like being bound by rules - find their own way to record. Using our own style to record our own time.",

        // Planner Wizard
        "planner.label": "~ Find Your Style ~",
        "planner.title": "Planner Style Quiz",
        "planner.subtitle": "A few questions to find your style",
        "planner.q1Title": "Who are you?",
        "planner.bgStudent": "Student",
        "planner.bgWorker": "Office Worker",
        "planner.bgParent": "Parent",
        "planner.bgFreelancer": "Freelancer",
        "planner.q2pjTitle": "Are you J or P?",
        "planner.q2pjHint": "MBTI Judging vs Perceiving dimension",
        "planner.jType": "J Type (Judging)",
        "planner.jTypeDesc": "Like planning, follow rules, enjoy routine",
        "planner.pType": "P Type (Perceiving)",
        "planner.pTypeDesc": "Like flexibility, spontaneous, dislike constraints",
        "planner.q3adhdTitle": "Your attention style?",
        "planner.q3adhdHint": "ADD/ADHD tendency self-assessment",
        "planner.adhdNone": "No significant tendency",
        "planner.adhdNoneDesc": "Attention stable, plans execute normally",
        "planner.adhdMild": "Mild tendency",
        "planner.adhdMildDesc": "Occasionally distracted, forget tasks, fuzzy time sense",
        "planner.adhdSignificant": "Significant tendency",
        "planner.adhdSignificantDesc": "Often distracted/hyperfocused, very fuzzy time sense",
        "planner.q4Title": "What do you want to track?",
        "planner.q4Hint": "Multi-select",
        "planner.goalTasks": "Manage Tasks",
        "planner.goalTime": "Track Time",
        "planner.goalHabits": "Track Habits",
        "planner.goalFeelings": "Record Feelings",
        "planner.goalReading": "Reading/Movie Log",
        "planner.q5Title": "Paper or Digital?",
        "planner.mediumPaper": "Paper Planner",
        "planner.mediumPaperDesc": "Handwriting feel, physical collection, free layout",
        "planner.mediumDigital": "Digital Planner",
        "planner.mediumDigitalDesc": "Record anytime, easy to modify, sync across devices",
        "planner.q6Title": "Do plans change often?",
        "planner.q6Hint": "Flexibility level",
        "planner.flexNever": "Rarely changes",
        "planner.flexNeverDesc": "Plans execute as planned after made",
        "planner.flexOccasional": "Occasional small changes",
        "planner.flexOccasionalDesc": "Plans sometimes need minor tweaks",
        "planner.flexFrequent": "Often small changes",
        "planner.flexFrequentDesc": "Plans adjust often, but direction stays",
        "planner.flexVeryFrequent": "Often major changes",
        "planner.flexVeryFrequentDesc": "Plans can't be made ahead, mostly spontaneous",
        "planner.flexVeryFrequentTip": "💡 Phone App recommended for this",
        "planner.q7Title": "Layout preference?",
        "planner.layoutCompact": "Compact",
        "planner.layoutCompactDesc": "More content per page, dense, practical",
        "planner.layoutSpacious": "Spacious",
        "planner.layoutSpaciousDesc": "More whitespace, can decorate, beautiful",
        "planner.q8Title": "How many things to record?",
        "planner.q8Hint": "Number of items to track per day",
        "planner.multiOne": "One thing",
        "planner.multiOneDesc": "Focus on the most important thing",
        "planner.multiFew": "A few things",
        "planner.multiFewDesc": "2-5 things, common situation",
        "planner.multiMany": "Many things",
        "planner.multiManyDesc": "Like recording every little detail",

        // Result
        "planner.recommended": "Recommended",
        "planner.resultTitle": "Your Recommended Types",
        "planner.resultNote": "💡 Combine 2-3 types\nAdd your own screenshots and images",
        "planner.restart": "Restart",
        "planner.getHelp": "Need Help? Contact Me",
        "planner.prev": "← Back",
        "planner.next": "Next →",
        "planner.yourProfile": "Your Profile",
        "planner.recommendedTypes": "Recommended Types",
        "planner.variant": "Recommended Variant",
        "planner.combinations": "Combination Tips",
        "planner.multiGoalTip": "Multiple goals - combine several types",
        "planner.pAdhdTip": "P Type + ADHD: Focus on recording over planning. Start with Timeline, then add To-do",
        "planner.highFlexTip": "Plans change often: Loose-leaf or Phone App for easy adjustment",
        "planner.paperFlexConflict": "Paper preference + frequent changes: Consider loose-leaf or paper + app combo",

        // Calendar
        "calendar.label": "~ Track ~",
        "calendar.title": "Journal Tracker",
        "calendar.subtitle": "Click to mark days",
        "calendar.days": "days",
        "calendar.streak": "streak",

        // Layout
        "layout.label": "~ Layout Tips ~",
        "layout.title": "Basic Layout Techniques",
        "layout.subtitle": "Simple theory to make your journal look better",
        "layout.whitespace.title": "Whitespace Rule",
        "layout.whitespace.desc": "Keep at least <strong>30% whitespace</strong> on each page. Don't fill every inch. Whitespace lets the page breathe.",
        "layout.alignment.title": "Alignment Rule",
        "layout.alignment.desc": "Choose one alignment and <strong>stay consistent</strong>. Left-align or center, but don't mix.",
        "layout.hierarchy.title": "Visual Hierarchy",
        "layout.hierarchy.desc": "Headlines <strong>big and bold</strong>, body text <strong>medium</strong>, notes <strong>small and light</strong>. Let readers see key points first.",
        "layout.proportion.title": "Image-Text Ratio",
        "layout.proportion.desc": "Images and decorations should be <strong>under 40%</strong> of the page. Text is the core, don't let images overwhelm it.",
        "layout.repetition.title": "Repetition",
        "layout.repetition.desc": "Use <strong>the same decorative elements</strong> (like stars, dots) as markers. Makes the whole journal feel cohesive.",
        "layout.colors.title": "Color Count",
        "layout.colors.desc": "Use <strong>no more than 3 colors</strong> per page. Too many colors look messy.",
        "layout.mainTip": "Most important: <strong>Layout makes content easier to read</strong>, not just prettier. If unsure, keep it simple!",

        // Q&A
        "qa.label": "~ Q&A ~",
        "qa.title": "Frequently Asked Questions",
        "qa.subtitle": "Common questions to help you start journaling",

        // Contact
        "contact.label": "~ Contact ~",
        "contact.title": "Let's Explore Together",
        "contact.intro": "Want a custom planner system? Questions? Contact me.",
        "contact.formName": "Name",
        "contact.formEmail": "Email",
        "contact.formMessage": "Message",
        "contact.formSubmit": "Send",

        // Footer
        "footer.tagline": "Sophie Planner ~ For Creative Minds",
        "footer.copyright": "Sophie Planner · since 2024"
    }
};